# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_ai_py/image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotobuf_ai_py/image.proto\"Y\n\x11ImageInferRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\"\\\n\x12ImageInferResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07results\x18\x06 \x03(\x02\x32K\n\x15ImageInferenceService\x12\x32\n\x05infer\x12\x12.ImageInferRequest\x1a\x13.ImageInferResponse\"\x00\x42\x0cZ\n./image/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_ai_py.image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./image/pb'
  _IMAGEINFERREQUEST._serialized_start=30
  _IMAGEINFERREQUEST._serialized_end=119
  _IMAGEINFERRESPONSE._serialized_start=121
  _IMAGEINFERRESPONSE._serialized_end=213
  _IMAGEINFERENCESERVICE._serialized_start=215
  _IMAGEINFERENCESERVICE._serialized_end=290
# @@protoc_insertion_point(module_scope)
