# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf_ai_py import lpr_pb2 as protobuf__ai__py_dot_lpr__pb2


class LprInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer = channel.unary_unary(
                '/LprInferenceService/infer',
                request_serializer=protobuf__ai__py_dot_lpr__pb2.LprInferRequest.SerializeToString,
                response_deserializer=protobuf__ai__py_dot_lpr__pb2.LprInferResponse.FromString,
                )


class LprInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LprInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer': grpc.unary_unary_rpc_method_handler(
                    servicer.infer,
                    request_deserializer=protobuf__ai__py_dot_lpr__pb2.LprInferRequest.FromString,
                    response_serializer=protobuf__ai__py_dot_lpr__pb2.LprInferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LprInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LprInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LprInferenceService/infer',
            protobuf__ai__py_dot_lpr__pb2.LprInferRequest.SerializeToString,
            protobuf__ai__py_dot_lpr__pb2.LprInferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
